[project]
name = "python-ml-dl"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "gradio>=6.17.3",
    "kmodes>=0.12.2",
    "matplotlib>=3.10.9",
    "mediapipe>=0.10.35",
    "notebook>=7.5.7",
    "numpy>=2.4.6",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.3",
    "pillow>=12.2.0",
    "pyinstaller>=6.21.0",
    "pyzbar>=0.1.9",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "ultralytics>=8.4.77",
    "wordcloud>=1.9.6",
]
